#!/bin/bash

# This script primarily grabs the version number from xLightsVersion.h or xlights_build_version.h
# and uses that to set the CFBundleVersion strings that are needed for the app store upload.
# This really just prevents having to adjust the xcodeproject version numbers every build


SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
if [ -f "${SCRIPTDIR}/../../xLights/xlights_build_version.h" ]; then
    XLVERSION=$(grep xlights_version_string ${SCRIPTDIR}/../../xLights/xlights_build_version.h | tr "\"" "\n" | grep 20)
else
    XLVERSION=$(grep xlights_version_string ${SCRIPTDIR}/../../xLights/xLightsVersion.h | tr "\"" "\n" | grep 20)
fi

# iff need to manually force a version number
#XLVERSION=2024.01.3
#That will create build number of 2401003


SHORTVER="${XLVERSION//./0}"
SHORTVERPFX="${SHORTVER:2:2}${SHORTVER:5:2}"
SHORTVERPO=${SHORTVER:8}
printf -v SHORTVERPO "%03d" $SHORTVERPO
SHORTVER="${SHORTVERPFX}${SHORTVERPO}"

cp $TARGET_BUILD_DIR/*.metallib $TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/Resources
cp $PROJECT_TEMP_ROOT/UninstalledProducts/macosx/*.metallib $TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/Resources

/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $XLVERSION" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $SHORTVER" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"


if [ -f "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/MacOS/xLights.debug.dylib" ]; then
    SRCLOCATION=`otool -L $TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/MacOS/xLights.debug.dylib | grep libwx_osx_cocoau_propgrid`
    #echo $SRCLOCATION > /tmp/foo.txt
    SRCLOCATION=${SRCLOCATION/\/libwx_osx_cocoau_propgrid*/}
    #echo $SRCLOCATION >> /tmp/foo.txt
    SRCINDEX=${#SRCLOCATION}
    #echo $SRCINDEX >> /tmp/foo.txt
    #SRCINDEX=$((SRCINDEX - 1))
    #echo $SRCINDEX >> /tmp/foo.txt

    LIBS=`otool -L $TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/MacOS/xLights.debug.dylib | grep xLights-macOS-dependencies | awk '{print $1}' | colrm 1 ${SRCINDEX}`
    echo $LIBS >> /tmp/foo.txt
    for LS in $LIBS
    do
       install_name_tool -change $SRCLOCATION/$LS @rpath/$LS  "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/MacOS/xLights.debug.dylib" 2> /dev/null
    done
    install_name_tool -add_rpath "${PROJECT_DIR}/dependencies/libdbg" "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/MacOS/xLights.debug.dylib" 2> /dev/null || true
fi



#if [ -z "${CODE_SIGN_IDENTITY}" ] ; then
#    exit 0
#fi

#if [ "$CONFIGURATION" != "Debug" ]; then
#    cd $TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/Frameworks
#    ls -1 *.dylib | xargs -n 1  /usr/bin/codesign  -f -v -s "$EXPANDED_CODE_SIGN_IDENTITY"
#fi


